preset: conventionalcommits
branches:
  - name: main
    prerelease: "rc"
  - name: release
plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - type: revert
          release: patch
        - type: perf
          release: patch
  # Build the binaries
  - - "@semantic-release/exec"
    # We use generateNotesCmd instead of a different step because it has access
    # to last/nextRelease due to when the step runs.
    - generateNotesCmd: "make release APP_VERSION=${nextRelease.version}"

  # This creates fancy release notes in our Github release
  - "@semantic-release/release-notes-generator"
  # Create the Github Release
  - - "@semantic-release/github"
    - assets:
        - "dist/*.tar.gz"
        - "dist/checksums.txt"

  ## <<Stencil::Block(customReleasePlugins)>>

  ## <</Stencil::Block>>
