[task_config]
includes = [".bootstrap/.mise/tasks", ".mise/tasks"]

[env]

## <<Stencil::Block(customMiseEnvironment)>>

## <</Stencil::Block>>

[tools]
bun = "1.2"
"npm:prettier" = "2"

## <<Stencil::Block(customMiseTools)>>

## <</Stencil::Block>>

## <<Stencil::Block(extraMise)>>

## <</Stencil::Block>>
