name: stencil
reportingTeam: fnd-dtss
description: microservice lifecycle manager
oss: true
slack: dev-tooling-notifications
library: true
commands:
  - stencil
circleAPIKey: ""
lintroller: platinum
releaseType: ""
releaseOptions:
  allowPrereleases: false
  allowMajorVersions: true
deployTo:
  environments: []
versions:
  go: 1.18.1
arguments:
  circleAPIKey: ""
  commands:
    - stencil
  dependencies:
    optional: []
    required: []
  description: microservice lifecycle manager
  grpcClients: []
  kubernetes:
    groups: []
  lintroller: platinum
  opslevel:
    confluenceSpaceKey: DTSS
    datadogDashboards:
      mainLink: ""
    designDocumentLink: https://docs.google.com/document/d/1e2YaeyeHMj5HrKMrZU8fh7-KInQj023GfzDxCi2u09A/edit
  oss: true
  releaseOptions:
    allowMajorVersions: true
    enablePrereleases: false
  reportingTeam: fnd-dtss
  service: false
  tutorial: false
  vaultSecrets:
    - deploy/honeycomb_new/%(environment)s/honeycomb
    - deploy/launchdarkly/%(environment)s/launchdarkly
    - deploy/mint/%(environment)s/validation/mint-validator-payload
    - deploy/flagship-shared-secret/%(environment)s/authn-flagship-payload
modules:
  - name: github.com/getoutreach/stencil-base
  - name: github.com/getoutreach/stencil-golang
  - name: github.com/getoutreach/stencil-opslevel
  - name: github.com/getoutreach/stencil-outreach
opsLevel:
  serviceTier: 0
  lifecycle: ""
  confluenceSpaceKey: DTSS
  pagerDutyLink: ""
  datadogDashboards:
    mainLink: ""
    custom: []
  designDocumentLink: https://docs.google.com/document/d/1e2YaeyeHMj5HrKMrZU8fh7-KInQj023GfzDxCi2u09A/edit
