name: stencil
reportingTeam: fnd-dtss
description: ""
oss: true
slack: ""
library: true
commands:
  - stencil
releaseType: ""
releaseOptions:
  allowPrereleases: false
  allowMajorVersions: true
deployTo:
  environments: []
arguments:
  dependencies:
    optional: []
    required: []
  description: ""
  reportingTeam: fnd-dtss
  type: []
modules:
  - url: https://github.com/getoutreach/stencil-base
    version: ""
