name: stencil
arguments:
  ciOptions:
    skipDocker: true
    skipE2e: true
  commands:
    - stencil
  confluenceSpaceKey: DT
  description: microservice lifecycle manager
  designDocumentLink: https://docs.google.com/document/d/1e2YaeyeHMj5HrKMrZU8fh7-KInQj023GfzDxCi2u09A/edit
  lintroller: platinum
  metrics: datadog
  notifications:
    releaseFailureSlackChannel: C01CEQP2MA6
  oss: true
  releaseOptions:
    allowMajorVersions: true
    autoPrereleases: true
    enablePrereleases: true
    prereleasesBranch: main
  reportingTeam: fnd-dt
  slack: dev-tooling-notifications
  tier: 2
  tracing: opentelemetry
  vaultSecrets:
    - deploy/honeycomb_new/%(environment)s/honeycomb
    - deploy/launchdarkly/%(environment)s/launchdarkly
    - deploy/mint/%(environment)s/validation/mint-validator-payload
    - deploy/flagship-shared-secret/%(environment)s/authn-flagship-payload
modules:
  - name: github.com/getoutreach/stencil-base
    channel: rc
  - name: github.com/getoutreach/stencil-golang
    channel: unstable
  - name: github.com/getoutreach/stencil-actions
    channel: rc
  - name: github.com/getoutreach/stencil-circleci
    channel: rc
  - name: github.com/getoutreach/devbase
    channel: rc
