name: stencil
reportingTeam: fnd-dtss
description: microservice lifecycle manager
oss: true
slack: dev-tooling-notifications
library: true
lintroller: platinum
commands:
  - stencil
circleAPIKey: ""
releaseType: ""
releaseOptions:
  allowPrereleases: false
  allowMajorVersions: true
deployTo:
  environments: []
versions:
  # we use the latest text/template additions
  go: 1.18
arguments:
  circleAPIKey: ""
  dependencies:
    optional: []
    required: []
  description: microservice lifecycle manager
  opslevel:
    confluenceSpaceKey: DTSS
    designDocumentLink: https://docs.google.com/document/d/1e2YaeyeHMj5HrKMrZU8fh7-KInQj023GfzDxCi2u09A/edit
  oss: true
  reportingTeam: fnd-dtss
  type:
    - library
modules:
  - url: https://github.com/getoutreach/stencil-base
    version: ""
opsLevel:
  serviceTier: 0
  lifecycle: ""
  confluenceSpaceKey: DTSS
  pagerDutyLink: ""
  datadogDashboards:
    mainLink: ""
    custom: []
  designDocumentLink: https://docs.google.com/document/d/1e2YaeyeHMj5HrKMrZU8fh7-KInQj023GfzDxCi2u09A/edit
