name: stencil

# Support bootstrap
library: true
oss: true
commands:
  - stencil
reportingTeam: fnd-dtss
releaseOptions:
  allowMajorVersions: true

# Support newer stencil
arguments:
  library: true
  commands:
    - stencil
  reportingTeam: fnd-dtss
  releaseOptions:
    allowMajorVersions: true
