name: stencil
reportingTeam: fnd-dt
description: microservice lifecycle manager
oss: true
slack: dev-tooling-notifications
library: true
commands:
  - stencil
circleAPIKey: ""
lintroller: platinum
tracing: honeycomb
metrics: datadog
releaseType: ""
releaseOptions:
  allowPrereleases: false
  prereleasesBranch: rc
  allowMajorVersions: true
deployTo:
  environments: []
versions:
  go: 1.18.1
arguments:
  circleAPIKey: ""
  commands:
    - stencil
  commitGuard: false
  dependencies:
    optional: []
    required: []
  description: microservice lifecycle manager
  grpcClients: []
  kubernetes:
    groups: []
  lintroller: platinum
  metrics: datadog
  opslevel:
    confluenceSpaceKey: DTSS
    datadogDashboards:
      mainLink: ""
    designDocumentLink: https://docs.google.com/document/d/1e2YaeyeHMj5HrKMrZU8fh7-KInQj023GfzDxCi2u09A/edit
  oss: true
  releaseOptions:
    allowMajorVersions: true
    enablePrereleases: false
    prereleasesBranch: rc
  reportingTeam: fnd-dt
  resources: {}
  service: false
  slack: dev-tooling-notifications
  terraform:
    datadog:
      grpc:
        evaluationWindow: ""
        latency:
          percentiles:
            highTraffic: 0
            lowTraffic: 0
          thresholds:
            highTraffic: 0
            lowTraffic: 0
        lowTrafficCountThreshold: 0
        qos:
          thresholds:
            highTraffic: 0
            lowTraffic: 0
        tags: []
      http:
        evaluationWindow: ""
        percentiles:
          highTraffic: 0
          lowTraffic: 0
        thresholds:
          highTraffic: 0
          lowCount: 0
          lowTraffic: 0
      pods:
        thresholds:
          availableLowCount: 0
  tracing: honeycomb
  tutorial: false
  vaultSecrets:
    - deploy/honeycomb_new/%(environment)s/honeycomb
    - deploy/launchdarkly/%(environment)s/launchdarkly
    - deploy/mint/%(environment)s/validation/mint-validator-payload
    - deploy/flagship-shared-secret/%(environment)s/authn-flagship-payload
modules:
  - name: github.com/getoutreach/stencil-circleci
  - name: github.com/getoutreach/stencil-actions
  - name: github.com/getoutreach/stencil-base
  - name: github.com/getoutreach/stencil-golang
  - name: github.com/getoutreach/stencil-outreach
opsLevel:
  serviceTier: 0
  lifecycle: ""
  confluenceSpaceKey: DTSS
  pagerDutyLink: ""
  datadogDashboards:
    mainLink: ""
    custom: []
  designDocumentLink: https://docs.google.com/document/d/1e2YaeyeHMj5HrKMrZU8fh7-KInQj023GfzDxCi2u09A/edit
