# Arguments

Documented below is a list of arguments provided by this stencil module. This documentation was
generated by `stencil docs generate`.

# Table of Contents
{{- /* Generate Table of Contents */}}

{{- range .Arguments }}
{{- $link := .Name | replace "." "" | printf "#%s" }}
{{ printf "- [%s](%s)" .Name $link }}
{{- end }}

{{- /* Generate Argument Documentation */}}
{{- range .Arguments }}

## {{ .Name }}

{{- if .Type }}
**Type**: `{{ .Type }}`
{{- else if .Types }}
**Types**: `{{ .Types | toJson }}`
{{- end }}
{{- if .Default }}
**Default**: `{{ .Default }}`
{{- end }}
{{- if .Required }}
**Required**: `{{ .Required }}`
{{- end }}
{{- if .Options }}
**Options**: `{{ .Options | toJson }}`
{{- end }}

{{ .Description }}
{{- end }}{{/* end range */}}
