# Please re-run stencil after any changes to this file as invalid
# syntax, such as anchors, will be fixed automatically.
version: 2.1
orbs:
  shared: getoutreach/shared@dev:codecov

# Extra contexts to expose to all jobs below
contexts: &contexts
  - aws-credentials
  - ghaccesstoken
  - docker-registry
  - npm-credentials
  - prismacloud-credentials
  - opslevel-credentials
  - vault-dev
  - confluence
  ## <<Stencil::Block(extraContexts)>>

  ## <</Stencil::Block>>

# Branches used for releasing code, pre-release or not
release_branches: &release_branches # Release branch
  - release
  # Pre-releases branch
  - "rc"
  # Unstable branch, e.g. HEAD development
  - "main"

jobs:
  ## <<Stencil::Block(circleJobs)>>
  integration:
    executor:
      name: shared/testbed-docker
      docker_tag: stable
    resource_class: medium+
    steps:
      - shared/setup_environment
      - shared/with_go_cache
      - run:
          name: Run integration tests
          no_output_timeout: 30m
          command: echo "Implement me!"
  ## <</Stencil::Block>>

  ### Start jobs inserted by other modules
  ### End jobs inserted by other modules

workflows:
  version: 2
  ## <<Stencil::Block(circleWorkflows)>>

  ## <</Stencil::Block>>

  ### Start workflows inserted by other modules
  ### End workflows inserted by other modules

  release:
    jobs:
      ## <<Stencil::Block(circleWorkflowJobs)>>
      - integration:
          context:
            - docker-registry
            - npm-credentials
            - ghaccesstoken
            - package-cloud-credentials
      ## <</Stencil::Block>>
      ### Start jobs inserted by other modules
      ### End jobs inserted by other modules
      - shared/release: &release
          dryrun: false
          context: *contexts
          ## <<Stencil::Block(circleReleaseExtra)>>

          ## <</Stencil::Block>>
          requires:
            ## <<Stencil::Block(circleReleaseRequires)>>
            - integration
            ## <</Stencil::Block>>
            - shared/test
          filters:
            branches:
              only: *release_branches

      # Dryrun release for PRs.
      - shared/release:
          <<: *release
          dryrun: true
          filters:
            branches:
              ignore: *release_branches
      - shared/test:
          context: *contexts
          app_name: stencil
          ### Start parameters inserted by other modules
          ### End parameters inserted by other modules
          ## <<Stencil::Block(circleTestExtra)>>

          ## <</Stencil::Block>>

      - shared/publish_docs:
          context: *contexts
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - shared/e2e:
          context: *contexts
          ## <<Stencil::Block(circleE2EExtra)>>

          ## <</Stencil::Block>>
      - shared/docker:
          context: *contexts
          filters:
            branches:
              ignore: *release_branches
            tags:
              only: /v\d+(\.\d+)*(-.*)*/
