
description = "A smart templating engine for service development"
## Setting this to true will add a "noindex" to *EVERY* page on the site..
removefromexternalsearch = false
## Gh repo for site footer (include trailing slash)
ghrepo = "https://github.com/getoutreach/strencil/"
## GH Repo for filing a new issue
github_repo = "https://github.com/getoutreach/strencil/issues/new"
### Edit content repo (set to automatically enter "edit" mode; this is good for "improve this page" links)
ghdocsrepo = "https://github.com/getoutreach/strencil-docs/"
## Gitter URL
gitter = ""
## Discuss Forum URL
forum = "https://github.com/getoutreach/stencil/discussions"
## Google Tag Manager
gtmid = ""

# First one is picked as the Twitter card image if not set on page.
images = ["/stencil/images/gohugoio-card.png"]

flex_box_interior_classes = "flex-auto w-100 w-40-l mr3 mb3 bg-white ba b--moon-gray nested-copy-line-height"

#sidebar_direction = "sidebar_left"