name: github pages

on:
  push:
    branches:
      - main # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup asdf
        uses: asdf-vm/actions/install@v1
      - name: Install hugo
        working-directory: ./docs
        run: |-
          # We run this here because of sub directory limitations
          asdf plugin add hugo
          asdf install

      - name: Build
        working-directory: ./docs
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
